openapi: 3.0.0
info:
  title: traPortfolio
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      operationId: getUsers
      description: ユーザー情報を取得します
      parameters:
        - schema:
            type: boolean
            default: 'false'
          in: query
          name: include-suspended
          description: アカウントがアクティブでないユーザーを含めるかどうか
  '/users/{userId}':
    parameters:
      - $ref: '#/components/parameters/userIdInPath'
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetail'
        '404':
          description: Not Found
      operationId: getUser
      description: ユーザー詳細情報を取得
    patch:
      summary: ''
      operationId: patchUser
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
components:
  schemas:
    User:
      title: User
      type: object
      description: ユーザー情報
      properties:
        id:
          type: string
          description: ユーザーUUID
          format: uuid
        name:
          type: string
          pattern: '^[a-zA-Z0-9_-]{1,32}$'
          description: ユーザー名
        displayName:
          type: string
          description: ユーザー表示名
          minLength: 0
          maxLength: 32
        iconFileId:
          type: string
          format: uuid
          description: アイコンファイルUUID
        bot:
          type: boolean
          description: BOTかどうか
        state:
          $ref: '#/components/schemas/UserAccountState'
        updatedAt:
          type: string
          description: 更新日時
          format: date-time
      required:
        - id
        - name
        - displayName
        - iconFileId
        - bot
        - state
        - updatedAt
      x-examples: {}
    UserAccountState:
      type: integer
      title: UserAccountState
      description: |-
        ユーザーアカウント状態
        0: 停止
        1: 有効
        2: 一時停止
      enum:
        - 0
        - 1
        - 2
      x-enum-varnames:
        - deactivated
        - active
        - suspended
      format: int32
    UserDetail:
      title: UserDetail
      type: object
      description: ユーザー詳細情報
      properties:
        id:
          type: string
          format: uuid
          description: ユーザーUUID
        state:
          $ref: '#/components/schemas/UserAccountState'
        bot:
          type: boolean
          description: BOTかどうか
        iconFileId:
          type: string
          format: uuid
          description: アイコンファイルUUID
        displayName:
          type: string
          description: ユーザー表示名
          minLength: 0
          maxLength: 32
        name:
          type: string
          pattern: '^[a-zA-Z0-9_-]{1,32}$'
          description: ユーザー名
        twitterId:
          type: string
          description: Twitter ID
          pattern: '^[a-zA-Z0-9_]{1,15}$'
        lastOnline:
          type: string
          description: 最終オンライン日時
          format: date-time
          nullable: true
        updatedAt:
          type: string
          format: date-time
          description: 更新日時
        tags:
          type: array
          description: タグリスト
          items:
            $ref: '#/components/schemas/UserTag'
        groups:
          type: array
          description: 所属グループのUUIDの配列
          items:
            type: string
            format: uuid
        bio:
          type: string
          description: 自己紹介(biography)
          maxLength: 1000
        homeChannel:
          type: string
          format: uuid
          description: ホームチャンネル
          nullable: true
      required:
        - id
        - state
        - bot
        - iconFileId
        - displayName
        - name
        - twitterId
        - lastOnline
        - updatedAt
        - tags
        - groups
        - bio
        - homeChannel
    UserTag:
      title: UserTag
      type: object
      description: ユーザータグ
      properties:
        tagId:
          type: string
          description: タグUUID
          format: uuid
        tag:
          type: string
          description: タグ文字列
        isLocked:
          type: boolean
          description: タグがロックされているか
        createdAt:
          type: string
          description: タグ付与日時
          format: date-time
        updatedAt:
          type: string
          format: date-time
          description: タグ更新日時
      required:
        - tagId
        - tag
        - isLocked
        - createdAt
        - updatedAt
  parameters:
    userIdInPath:
      name: userId
      in: path
      required: true
      description: ユーザーUUID
      schema:
        type: string
        format: uuid
    projectIdInPath:
      name: projectId
      in: path
      required: true
      description: プロジェクトUUID
      schema:
        type: string
        format: uuid
    eventIdInPath:
      name: eventId
      in: path
      required: true
      description: イベントUUID
      schema:
        type: string
        format: uuid
