linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gofmt
    - revive
    - testpackage

run:
  build-tags:
    - integration
    - db

linters-settings:
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: '1.17'
