dsn: mariadb://root:password@localhost:3306/portfolio?parseTime=true
docPath: docs/dbschema
er:
  format: mermaid

lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
    exclude:
      - id
      - created_at
      - updated_at
      - deleted_at

comments:
  - table: users
    tableComment: ユーザーテーブル
    columnComments:
      id: ユーザーUUID
      description: 自己紹介文
      check: "氏名を公開するかどうかの可否 (0: 停止, 1: 有効, 2: 一時停止)"
      name: ユーザー名
      state: traQのユーザーアカウント状態
  - table: event_level_relations
    tableComment: knoQイベントと公開レベルの関係テーブル
    columnComments:
      id: knoQイベントUUID
      level: 公開レベル。0なら匿名、1ならそのまま公開、2なら外部に非公開
      created_at: 関係テーブル作成日時
      updated_at: 関係テーブル更新日時
  - table: contests
    tableComment: コンテストテーブル
    columnComments:
      id: コンテストUUID
      name: コンテスト名
      description: コンテスト説明
      link: コンテスト情報のリンク
      since: 期間始まり
      until: 期間終わり
      created_at: コンテスト作成日時
      updated_at: コンテスト更新日時
  - table: contest_teams
    tableComment: コンテスト参加チームテーブル
    columnComments:
      id: コンテストチームUUID
      contest_id: コンテストUUID
      name: チーム名
      description: チーム情報
      result: 順位などの結果
      link: コンテストチームの詳細が載っているページへのリンク
      created_at: コンテストチーム作成日時
      updated_at: コンテストチーム更新日時
  - table: contest_team_user_belongings
    tableComment: コンテストチームとユーザー関係テーブル
    columnComments:
      team_id: コンテストチームUUID
      user_id: ユーザーUUID
      created_at: 関係テーブル作成日時
      updated_at: 関係テーブル更新日時
  - table: migrations
    tableComment: gormigrate用のデータベースバージョンテーブル
  - table: accounts
    tableComment: Twitterなどのアカウントテーブル
    columnComments:
      id: アカウントUUID
      type: アカウントのハードコードID
      name: アカウント名
      url: アカウントのURL
      user_id: ユーザーUUID
  - table: projects
    tableComment: プロジェクトテーブル
    columnComments:
      id: プロジェクトUUID
      name: プロジェクト名
      description: プロジェクト説明
      link: プロジェクト情報のリンク
      since_year: プロジェクト開始年
      since_semester: プロジェクト開始学期(0:前期 1:後期)
      until_year: プロジェクト終了年
      until_semester: プロジェクト終了学期(0:前期 1:後期)
      created_at: プロジェクト作成日時
      updated_at: プロジェクト更新日時
  # - table: achievements
  #   tableComment: 実績情報
  #   columnComments:
  #     id: 実績UUID
  #     name: 実績名
  #     description: 実績の説明
  - table: project_members
    tableComment: プロジェクト所属者テーブル
    columnComments:
      project_id: プロジェクトUUID
      user_id: ユーザーUUID
      since_year: プロジェクト所属開始年
      since_semester: プロジェクト所属開始学期(0:前期 1:後期)
      until_year: プロジェクト所属終了年
      until_semester: プロジェクト所属終了学期(0:前期 1:後期)
  # - table: achievements_members
  #   tableComments: 実績メンバーテーブル
  #   columnComments:
  #     achievement_id: 実績UUID
  #     user_id: ユーザーUUID
  - table: groups
    tableComment: グループテーブル
    columnComments:
      group_id: グループUUID
      name: グループ名
      link: グループのリンク
      description: グループの説明文
      created_at: グループ作成日時
      updated_at: グループ更新日時
  - table: group_user_belongings
    tableComment: グループとユーザー関係テーブル
    columnComments:
      user_id: ユーザーUUID
      group_id: グループUUID
      since_year: ユーザー所属開始年
      since_semester: ユーザー所属開始学期(0:前期 1:後期)
      until_year: ユーザー所属終了年
      until_semester: ユーザー所属終了学期(0:前期 1:後期)
      created_at: 関係テーブル作成日時
      updated_at: 関係テーブル更新日時
  - table: group_user_admins
    tableComment: グループと管理者関係テーブル
    columnComments:
      user_id: ユーザーUUID
      group_id: グループUUID
      created_at: 関係テーブル作成日時
      updated_at: 関係テーブル更新日時
