services:
  backend:
    build: ./
    restart: always
    environment:
      TPF_PORT: "1323"
      TPF_DB_USER: "root"
      TPF_DB_PASS: "password"
      TPF_DB_HOST: "mysql"
      TPF_DB_NAME: "portfolio"
      TPF_DB_PORT: "3306"
    ports:
      - "1323:1323"
    depends_on:
      mysql:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  mysql:
    image: mariadb:10.6.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
    # conohaのDBのデフォルトCharsetはutf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:standalone
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha
    ports:
      - "3001:8080"
