services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  backend:
    build: ./
    restart: always
    environment:
      TPF_PORT: "1323"
      TPF_DB_USER: "root"
      TPF_DB_PASS: "password"
      TPF_DB_HOST: "mysql"
      TPF_DB_NAME: "portfolio"
      TPF_DB_PORT: "3306"
    ports:
      - "1323:1323"
    depends_on:
      mysql:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./

  ui:
    image: ghcr.io/traptitech/traportfolio-ui:main
    restart: always
    expose:
      - "80"
    depends_on:
      - backend

  dashboard:
    image: ghcr.io/traptitech/traportfolio-dashboard:main
    restart: always
    expose:
      - "80"
    depends_on:
      - backend

  mysql:
    image: mariadb:10.6.4@sha256:c014ba1efc5dbd711d0520c7762d57807f35549de3414eb31e942a420c8a2ed2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
    # conohaのDBのデフォルトCharsetはutf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute "SHOW DATABASES;"
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:standalone@sha256:cc64d253db4f016cbcff2ff2f01e60ed07e74f38b4398f84d3c4fae4b5ce0e07
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha
    ports:
      - "3001:8080"

volumes:
  caddy_data:
  caddy_config:
