version: "3"

services:
  backend:
    build: ./
    restart: always
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./traPortfolio
    environment:
      KNOQ_COOKIE: ${KNOQ_COOKIE}
      KNOQ_API_ENDPOINT: ${KNOQ_API_ENDPOINT}
      TRAQ_COOKIE: ${TRAQ_COOKIE}
      TRAQ_API_ENDPOINT: ${TRAQ_API_ENDPOINT}
      PORTAL_COOKIE: ${PORTAL_COOKIE}
      PORTAL_API_ENDPOINT: ${PORTAL_API_ENDPOINT}
    expose:
      - "80"
      - "6060"
    ports:
      - "1323:1323"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
    # conohaのDBのデフォルトCharsetはutf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    expose:
      - "8080"
    ports:
      - "3001:8080"

  # TODO: ポート番号を決める
  mock_traq:
    image: stoplight/prism:3
    restart: always
    expose:
      - "4010"
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 -p 4010 -d "https://raw.githubusercontent.com/traPtitech/traQ/master/docs/v3-api.yaml"


  mock_portal:
    image: stoplight/prism:3
    restart: always
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    expose:
      - "4011"
    ports:
      - "4011:4011"
    command: mock -h 0.0.0.0 -p 4011 -d "https://raw.githubusercontent.com/traPtitech/portal/master/document/swagger.yaml?token=${GITHUB_TOKEN}"

  mock_knoq:
    image: stoplight/prism:3
    restart: always
    expose:
      - "4012"
    ports:
      - "4012:4012"
    command: mock -h 0.0.0.0 -p 4012 -d "https://raw.githubusercontent.com/traPtitech/knoQ/master/docs/swagger.yaml"
