version: "3"

services:
  backend:
    build: ./
    restart: always
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./traPortfolio
    environment:
      KNOQ_COOKIE: ${KNOQ_COOKIE}
      KNOQ_API_ENDPOINT: ${KNOQ_API_ENDPOINT}
      TRAQ_COOKIE: ${TRAQ_COOKIE}
      TRAQ_API_ENDPOINT: ${TRAQ_API_ENDPOINT}
      PORTAL_COOKIE: ${PORTAL_COOKIE}
      PORTAL_API_ENDPOINT: ${PORTAL_API_ENDPOINT}
    expose:
      - "80"
      - "6060"
    ports:
      - "1323:1323"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.6.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
    # conohaのDBのデフォルトCharsetはutf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    expose:
      - "8080"
    ports:
      - "3001:8080"
