// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/golang/mock/gomock"
	"github.com/google/wire"
	"github.com/traPtitech/traPortfolio/usecases/service"
	"github.com/traPtitech/traPortfolio/usecases/service/mock_service"
)

// Injectors from test_wire.go:

func SetupTestApi(ctrl *gomock.Controller) TestHandlers {
	pingHandler := NewPingHandler()
	mockUserService := mock_service.NewMockUserService(ctrl)
	userHandler := NewUserHandler(mockUserService)
	mockProjectService := mock_service.NewMockProjectService(ctrl)
	projectHandler := NewProjectHandler(mockProjectService)
	mockEventService := mock_service.NewMockEventService(ctrl)
	eventHandler := NewEventHandler(mockEventService)
	mockContestService := mock_service.NewMockContestService(ctrl)
	contestHandler := NewContestHandler(mockContestService)
	api := NewAPI(pingHandler, userHandler, projectHandler, eventHandler, contestHandler)
	testService := TestService{
		MockContestService: mockContestService,
		MockEventService:   mockEventService,
		MockProjectService: mockProjectService,
		MockUserService:    mockUserService,
	}
	testHandlers := TestHandlers{
		API:     api,
		Service: testService,
	}
	return testHandlers
}

// test_wire.go:

var mockPingSet = wire.NewSet(
	NewPingHandler,
)

var mockUserSet = wire.NewSet(mock_service.NewMockUserService, NewUserHandler, wire.Bind(new(service.UserService), new(*mock_service.MockUserService)))

var mockProjectSet = wire.NewSet(mock_service.NewMockProjectService, NewProjectHandler, wire.Bind(new(service.ProjectService), new(*mock_service.MockProjectService)))

var mockEventSet = wire.NewSet(mock_service.NewMockEventService, NewEventHandler, wire.Bind(new(service.EventService), new(*mock_service.MockEventService)))

var mockContestSet = wire.NewSet(mock_service.NewMockContestService, NewContestHandler, wire.Bind(new(service.ContestService), new(*mock_service.MockContestService)))

var mockApiSet = wire.NewSet(NewAPI)
