output: schema_gen.go
generate:
  models: true
package: schema
output-options:
  user-templates:
    # https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/templates/request-bodies.tmpl
    request-bodies.tmpl: |
      {{range .}}{{end}}{{/* write nothing */}}
