// Code generated by MockGen. DO NOT EDIT.
// Source: contest.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/traPtitech/traPortfolio/domain"
	repository "github.com/traPtitech/traPortfolio/usecases/repository"
)

// MockContestService is a mock of ContestService interface.
type MockContestService struct {
	ctrl     *gomock.Controller
	recorder *MockContestServiceMockRecorder
}

// MockContestServiceMockRecorder is the mock recorder for MockContestService.
type MockContestServiceMockRecorder struct {
	mock *MockContestService
}

// NewMockContestService creates a new mock instance.
func NewMockContestService(ctrl *gomock.Controller) *MockContestService {
	mock := &MockContestService{ctrl: ctrl}
	mock.recorder = &MockContestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContestService) EXPECT() *MockContestServiceMockRecorder {
	return m.recorder
}

// AddContestTeamMembers mocks base method.
func (m *MockContestService) AddContestTeamMembers(ctx context.Context, teamID uuid.UUID, memberIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContestTeamMembers", ctx, teamID, memberIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContestTeamMembers indicates an expected call of AddContestTeamMembers.
func (mr *MockContestServiceMockRecorder) AddContestTeamMembers(ctx, teamID, memberIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContestTeamMembers", reflect.TypeOf((*MockContestService)(nil).AddContestTeamMembers), ctx, teamID, memberIDs)
}

// CreateContest mocks base method.
func (m *MockContestService) CreateContest(ctx context.Context, args *repository.CreateContestArgs) (*domain.ContestDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContest", ctx, args)
	ret0, _ := ret[0].(*domain.ContestDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContest indicates an expected call of CreateContest.
func (mr *MockContestServiceMockRecorder) CreateContest(ctx, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContest", reflect.TypeOf((*MockContestService)(nil).CreateContest), ctx, args)
}

// CreateContestTeam mocks base method.
func (m *MockContestService) CreateContestTeam(ctx context.Context, contestID uuid.UUID, args *repository.CreateContestTeamArgs) (*domain.ContestTeamDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContestTeam", ctx, contestID, args)
	ret0, _ := ret[0].(*domain.ContestTeamDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContestTeam indicates an expected call of CreateContestTeam.
func (mr *MockContestServiceMockRecorder) CreateContestTeam(ctx, contestID, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContestTeam", reflect.TypeOf((*MockContestService)(nil).CreateContestTeam), ctx, contestID, args)
}

// DeleteContest mocks base method.
func (m *MockContestService) DeleteContest(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContest", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContest indicates an expected call of DeleteContest.
func (mr *MockContestServiceMockRecorder) DeleteContest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContest", reflect.TypeOf((*MockContestService)(nil).DeleteContest), ctx, id)
}

// DeleteContestTeam mocks base method.
func (m *MockContestService) DeleteContestTeam(ctx context.Context, contestID, teamID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContestTeam", ctx, contestID, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContestTeam indicates an expected call of DeleteContestTeam.
func (mr *MockContestServiceMockRecorder) DeleteContestTeam(ctx, contestID, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContestTeam", reflect.TypeOf((*MockContestService)(nil).DeleteContestTeam), ctx, contestID, teamID)
}

// DeleteContestTeamMembers mocks base method.
func (m *MockContestService) DeleteContestTeamMembers(ctx context.Context, teamID uuid.UUID, memberIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContestTeamMembers", ctx, teamID, memberIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContestTeamMembers indicates an expected call of DeleteContestTeamMembers.
func (mr *MockContestServiceMockRecorder) DeleteContestTeamMembers(ctx, teamID, memberIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContestTeamMembers", reflect.TypeOf((*MockContestService)(nil).DeleteContestTeamMembers), ctx, teamID, memberIDs)
}

// GetContest mocks base method.
func (m *MockContestService) GetContest(ctx context.Context, id uuid.UUID) (*domain.ContestDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContest", ctx, id)
	ret0, _ := ret[0].(*domain.ContestDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContest indicates an expected call of GetContest.
func (mr *MockContestServiceMockRecorder) GetContest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContest", reflect.TypeOf((*MockContestService)(nil).GetContest), ctx, id)
}

// GetContestTeam mocks base method.
func (m *MockContestService) GetContestTeam(ctx context.Context, contestID, teamID uuid.UUID) (*domain.ContestTeamDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestTeam", ctx, contestID, teamID)
	ret0, _ := ret[0].(*domain.ContestTeamDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestTeam indicates an expected call of GetContestTeam.
func (mr *MockContestServiceMockRecorder) GetContestTeam(ctx, contestID, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestTeam", reflect.TypeOf((*MockContestService)(nil).GetContestTeam), ctx, contestID, teamID)
}

// GetContestTeamMembers mocks base method.
func (m *MockContestService) GetContestTeamMembers(ctx context.Context, contestID, teamID uuid.UUID) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestTeamMembers", ctx, contestID, teamID)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestTeamMembers indicates an expected call of GetContestTeamMembers.
func (mr *MockContestServiceMockRecorder) GetContestTeamMembers(ctx, contestID, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestTeamMembers", reflect.TypeOf((*MockContestService)(nil).GetContestTeamMembers), ctx, contestID, teamID)
}

// GetContestTeams mocks base method.
func (m *MockContestService) GetContestTeams(ctx context.Context, contestID uuid.UUID) ([]*domain.ContestTeam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestTeams", ctx, contestID)
	ret0, _ := ret[0].([]*domain.ContestTeam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestTeams indicates an expected call of GetContestTeams.
func (mr *MockContestServiceMockRecorder) GetContestTeams(ctx, contestID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestTeams", reflect.TypeOf((*MockContestService)(nil).GetContestTeams), ctx, contestID)
}

// GetContests mocks base method.
func (m *MockContestService) GetContests(ctx context.Context) ([]*domain.Contest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContests", ctx)
	ret0, _ := ret[0].([]*domain.Contest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContests indicates an expected call of GetContests.
func (mr *MockContestServiceMockRecorder) GetContests(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContests", reflect.TypeOf((*MockContestService)(nil).GetContests), ctx)
}

// UpdateContest mocks base method.
func (m *MockContestService) UpdateContest(ctx context.Context, id uuid.UUID, args *repository.UpdateContestArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContest", ctx, id, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContest indicates an expected call of UpdateContest.
func (mr *MockContestServiceMockRecorder) UpdateContest(ctx, id, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContest", reflect.TypeOf((*MockContestService)(nil).UpdateContest), ctx, id, args)
}

// UpdateContestTeam mocks base method.
func (m *MockContestService) UpdateContestTeam(ctx context.Context, teamID uuid.UUID, args *repository.UpdateContestTeamArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContestTeam", ctx, teamID, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContestTeam indicates an expected call of UpdateContestTeam.
func (mr *MockContestServiceMockRecorder) UpdateContestTeam(ctx, teamID, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContestTeam", reflect.TypeOf((*MockContestService)(nil).UpdateContestTeam), ctx, teamID, args)
}
