// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package infrastructure

import (
	"github.com/google/wire"
	"github.com/traPtitech/traPortfolio/interfaces/repository"
	"github.com/traPtitech/traPortfolio/usecases/handler"
	repository2 "github.com/traPtitech/traPortfolio/usecases/repository"
	"github.com/traPtitech/traPortfolio/usecases/usecase"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func InjectAPIServer() (handler.API, error) {
	pingHandler := handler.NewPingHandler()
	sqlHandler, err := NewSQLHandler()
	if err != nil {
		return handler.API{}, err
	}
	userRepository := repository.NewUserRepository(sqlHandler)
	userHandler := handler.NewUserHandler(userRepository)
	api := handler.NewAPI(pingHandler, userHandler)
	return api, nil
}

// wire.go:

var pingSet = wire.NewSet(handler.NewPingHandler, wire.Bind(new(usecase.PingUsecase), new(*handler.PingHandler)))

var userSet = wire.NewSet(repository.NewUserRepository, handler.NewUserHandler, wire.Bind(new(repository2.UserRepository), new(*repository.UserRepository)), wire.Bind(new(usecase.UserUsecase), new(*handler.UserHandler)))

var sqlSet = wire.NewSet(NewSQLHandler)

var apiSet = wire.NewSet(handler.NewAPI)
