name: Build image

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: traportfolio

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF:10})
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }}
            ghcr.io/traptitech/${{ env.IMAGE_NAME }}:latest

