name: swagger docs
on:
  push:
    paths:
      - "docs/swagger/traPortfolio.v1.yaml"
    branches:
      - "master"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs/_built
          spec-file: docs/swagger/traPortfolio.v1.yaml
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs/_built --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
